# -*- coding: utf-8 -*-
"""Cajero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3BeXrHUw8Tfjk88ny17KKJ1yLdcOQpf
"""

import pandas as pd

data = {
    "Nombre": ["Juan", "María", "Pedro", "Ana", "Luis", "Carlos", "Leandro", "Sofía", "David", "Laura"],
    "Clave de Banco": ["888888888", "987654321", "111111111", "222222222", "333333333", "444444444", "123456789", "555555555", "666666666", "777777777"],
    "Saldo": [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
}

df = pd.DataFrame(data)
print(df)

Continuar = False
Usuario = None
Ingreso = input('!Bienvenido estimado cliente, porfavor ingrese su número de cuenta: ')
for index, row in df.iterrows():
    if row["Clave de Banco"] == Ingreso:
        print(f"Bienvenido {row['Nombre']}")
        Continuar = True
        Usuario = row
        break

if Usuario is not None:
  saldo = Usuario['Saldo']
  while Continuar:
    print(" 1.Consultar saldo\n 2.Retirar dinero\n 3.Depositar dinero\n 4.Transferir dinero a otra cuenta\n 5.Salir\n")
    opcion = int(input(" Ingrese la opción deseada: "))

    if opcion == 1:
        print(f"Su saldo actual es de {saldo}$ ¡Gracias por consultar!\n")

    elif opcion == 2:
        retiro = int(input('Cuanto desea retirar?: \n'))
        if retiro > saldo:
            print('No tiene fondos suficientes')
        else:
            saldo -= retiro
            print(f'Retiro de {retiro} realizado exitosamente\n')

    elif opcion == 3:
        deposito = int(input('Cuanto desea depositar?: \n'))
        saldo += deposito
        print(f'Deposito {deposito} realizado exitosamente, su saldo actual es {saldo}\n')

    elif opcion == 4:
        cuenta = input('ingrese la cuenta destino: \n')
        cantidad = int(input('Ingrese cantidad a enviar: \n'))

        if cantidad > saldo:
            print('No tiene fondos suficientes')
        else:
            print(f'Se envio {cantidad} a la cuenta {cuenta}\n')
            saldo -= cantidad
            print(f'Su saldo actual es de {saldo}$\n')

    else:
        print('Gracias por su visita')
        Usuario = None
        break

else:
  print('Sesión aún no iniciada')